### ISSUE TITLE
About tune_loss_weight (for a different dataset)

### ISSUE THREAD

**Issue by iwyoo** [KelvinZx/sfcn-opi#1]
Thanks for the nice implementation!

I have a question about the tune_loss_weight function in 'model.py'.
I found that you used fixed weights to balance loss functions.
How do you find the proper weight values? 
I want to apply this method to a new dataset, but it is very hard to search the weights by hands.
Is there any good strategy to find a proper loss weight?

**Comment by xmoanvaf** [comment]
Sorry for the late reply.
In fact there is no convenient way to find the hyper parameters, i tried to use grid search but there is just too many hyper parameters in the loss function, yet this model is extremely sensitive to these parameters.

I have asked the author who wrote the paper about this issue and they provide some hyper parameters for me to validate their result. And i'm afraid that you will needs to tune these parameters if you want to apply it to a new dataset.

**Comment by iwyoo** [comment]
It is unavoidable, then I should enjoy it. Thanks for your kind comment!
